In [1]:
import numpy as np

# Creating arrays
arr1d = np.array([1, 2, 3, 4])
arr2d = np.array([[1, 2, 3], [4, 5, 6]])

# Useful array creation helpers
zeros = np.zeros((2, 3))       # 2x3 matrix filled with 0.0
ones = np.ones((3, 3))         # 3x3 matrix filled with 1.0
rang = np.arange(0, 10, 2)     # Array from 0 to 8 with step 2: [0, 2, 4, 6, 8]
space = np.linspace(0, 1, 5)    # 5 evenly spaced points between 0 and 1

In [2]:
a = np.array([[10, 20, 30], [40, 50, 60]])

print(a.ndim)   # Output: 2
print(a.shape)  # Output: (2, 3)
print(a.size)   # Output: 6
print(a.dtype)  # Output: int64 (or int32 depending on system)

2
(2, 3)
6
int64


In [3]:
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Access single element: array[row, col]
print(m[0, 1])     # Output: 2

# Slicing: array[row_slice, col_slice]
print(m[0:2, 1:3]) # Output: [[2, 3], [5, 6]]

# Boolean Indexing (Filtering)
mask = m > 5
print(m[mask])     # Output: [6, 7, 8, 9]

2
[[2 3]
 [5 6]]
[6 7 8 9]


In [4]:
arr = np.array([1, 2, 3, 4])

# Arithmetic operations (element-wise)
print(arr + 10)       # Output: [11, 12, 13, 14]
print(arr * 2)        # Output: [2, 4, 6, 8]

# Mathematical functions (ufuncs)
print(np.sqrt(arr))   # Square root of each element
print(np.exp(arr))    # Exponential (e^x) of each element

[11 12 13 14]
[2 4 6 8]
[1.         1.41421356 1.73205081 2.        ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [5]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])  # Shape (2, 3)
row = np.array([10, 20, 30])               # Shape (3,)

# The 1D array is automatically stretched to match the 2D matrix shape
result = matrix + row
print(result)
# Output:
# [[11, 22, 33]
#  [14, 25, 36]]

[[11 22 33]
 [14 25 36]]


In [6]:
x = np.arange(6)             # [0, 1, 2, 3, 4, 5]

# Reshape to 2x3
grid = x.reshape((2, 3))     # [[0, 1, 2], [3, 4, 5]]

# Transpose (swap rows and columns)
transposed = grid.T          # Shape becomes (3, 2)

# Flatten (convert to 1D)
flat = grid.flatten()        # [0, 1, 2, 3, 4, 5]

In [7]:
data = np.array([[1, 2], [3, 4]])

print(np.sum(data))         # Output: 10 (Sum of all elements)
print(np.sum(data, axis=0)) # Output: [4, 6] (Column-wise sums)
print(np.sum(data, axis=1)) # Output: [3, 7] (Row-wise sums)
print(np.mean(data))        # Output: 2.5

10
[4 6]
[3 7]
2.5
